### ISSUE TITLE
Problem with the third option: app/bootstrap not found

### ISSUE THREAD

**Issue by camilosampedro** [joost-de-vries/play-angular2-typescript#15]
Hi!

I was trying to execute the third option, where a single JavaScript is generated and provided by the server. I have no problem with the second option, multiple files compiled by the server and provided separately.

The problem I got was that `app/bootstrap` is not found on the main page.

I changed the `Application` controller to return `index2.scala.html` and passed the jvm parameter `-DtsCompileMode=stage` when running:

``` bash
activator ~run -DtsCompileMode=stage
```

The browser tells me that it finds the `main.js`, the problem is when loading `app/bootstrap` [here](https://github.com/joost-de-vries/play-angular2-typescript/blob/master/app/views/index2.scala.html#L21); it tries to download a `localhost/app/bootstrap` instead of loading it from `main.js` (I checked and it is not inside `main.js`).

I don't know if I am doing something wrong, if something is missing or if this is a bug.

Thank you! 😄

**Comment by joost-de-vries** [comment]
Yeah. That third option hasn't been ported to angular2 final yet.
There's a previous issue about this. #11  Join us there pls.
