### ISSUE TITLE
coursier.ResolutionException: Conflict(s) in dependency resolution

### ISSUE THREAD

**Issue by mkstayalive** [joost-de-vries/play-angular2-typescript#16]
Hi, I'm trying to run the sbt application, but I'm getting the following error

```
coursier.ResolutionException: Conflict(s) in dependency resolution:
  org.webjars.npm:glob:5.0.15:default(compile)
org.webjars.npm:glob:7.0.6:default(compile)
[error] (*:coursierResolution) coursier.ResolutionException: Conflict(s) in dependency resolution:
[error]   org.webjars.npm:glob:5.0.15:default(compile)
[error] org.webjars.npm:glob:7.0.6:default(compile)
```
I have tried with both activator run and sbt run. Tried creating an app using `activator new` and also by cloning the repository. The same error comes up in all cases.

**Comment by joost-de-vries** [comment]
I don't recognise the exception out of Coursier. There's no coursier sbt plugin in the play-angular2-typescript project.
Is that an sbt plugin that you installed yourself? Maybe globally?

**Comment by mkstayalive** [comment]
@joost-de-vries Thanks. You are right. There was a global coursier plugin that I had installed. In `~/.sbt/0.13/plugins/plugins.sbt` I had this line

```
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M14")
```

Removing it fixed the issue. However I'm not sure why this exception is occurring only for this particular play project. All other projects are working fine.
