### ISSUE TITLE
Property not passed to the top level component

### ISSUE THREAD

**Issue by cduicu** [joost-de-vries/play-angular2-typescript#17]
I am not able to pass properties into the component. Here are the changes to reproduce the issue:
- modify _app/views/index1.scala.html_:
`<todo-app myprop="someValue"></todo-app>`

- modify _app/assets/app/app.ts_ to import Input and add the property:
```
import {Component, Input} from "@angular/core"
.....
export default class TodoAppComponent implements OnInit {
    @Input() myprop:string
.....
```
At runtime the _myprop_ property will be undefined. I noticed that the issue is only with the top level component from the scala.html file. I was able to pass properties to components under the app/assets/app.

**Comment by joost-de-vries** [comment]
Hi cduicu, this is general Angular2 question. Not an issue with the play-angular2-typescript project. I advise you to ask your question of Stackoverflow or something like that.

**Comment by cduicu** [comment]
You are right, joost-de-vries! Found an open ticket for this: [https://github.com/angular/angular/issues/1858]. The elementRef workaround described there works fine, so this is not an issue.
