### ISSUE TITLE
angular2/router

### ISSUE THREAD

**Issue by carlosFattor** [joost-de-vries/play-angular2-typescript#2]
Hello,
Congratulations for your job...

I have a problem trying to use it, when I try to config "angular2/router" an error occurs, the folowing error:
=> "NetworkError: 404 Not Found - http://localhost:9000/angular2/router" <=
Do you have any idea about this?

thanks.

**Comment by joost-de-vries** [comment]
There's no such url defined anywhere in this demo application I don't believe.
So I'm not sure it's an issue for this github repo.

**Comment by carlosFattor** [comment]
Hello,
sorry, but I think that I'm not explaining correctly... When I tried to import "angular2/router" and try to configure "@RouteConfig", this error happens, it's how if the library not found! When I remove the configuration, all come back to run normally. That's happening.

**Comment by carlosFattor** [comment]
Sorry, I founded what was the problem, I forgot the include import "<script src='@routes.Assets.versioned("lib/angular2/bundles/router.dev.js")'></script>", problem solved...
