### ISSUE TITLE
Running test under karma with jasmine

### ISSUE THREAD

**Issue by Starfight** [joost-de-vries/play-angular2-typescript#23]
I have successfully build my play application with Angular front-end thanks to your project template. 
Now I search to test my code Typescript code using karma and jasmine. I have see you have a `test` directory and you import `jasmine-core` and `types__jasmine` but I don't know how to use it with sbt. Is it possible or need I use external command ?

EDIT: Maybe it was helpfull to use [sbt-mocha](https://github.com/sbt/sbt-mocha) instead of karma but I got an `Error: Cannot find module 'internal/fs'`

**Comment by joost-de-vries** [comment]
Hm. To be honest: running ng2 jasmine tests has been something that I wanted to get to work for a long time. I implemented an [sbt-jasmine](https://github.com/joost-de-vries/sbt-jasmine) plugin especially for that. 
Unfortunately I'm no longer doing an Angular2 project. So it's hard to find the time to fiddle with setting up the SystemJS dependencies that are required to be in memory when your run the tests.
Would you like to make a pull request using sbt-jasmine?
