### ISSUE TITLE
Unexpected exception languageServiceHost.js:21 ReferenceError: Map is not defined

### ISSUE THREAD

**Issue by bravegag** [joost-de-vries/play-angular2-typescript#24]
I need a working copy of this seed example for a new application. When I clone and run get the error below. What is the issue and how can be solved? Oh I checked and the same error happens in travis I see that the build is broken there with this same issue ... I don't feel too bad now :) but would be nice if it is fixed or someone help me figure out how to fix it.

![screenshot from 2017-03-10 08 57 28](https://cloud.githubusercontent.com/assets/4385408/23786932/d98a8568-056f-11e7-8943-e00a2bfb3945.png)

**Comment by joost-de-vries** [comment]
Do you have a recent version of NodeJs installed on your system?
Map cannot be found by your JS engine. And Map is an ES6 feature that is available by default on most versions of NodeJS I think.

**Comment by bravegag** [comment]
Hi Joost-de-vries, thank you for your answer. I'm running Ubuntu/Firefox .. I didn't know that NodeJS was required in addition to the project dependencies ... however, I run the same on Windows IE and it worked np .. it is so strange.

**Comment by joost-de-vries** [comment]
If I understand correctly your problem has been solved.
