### ISSUE TITLE
how to use libarary.such as ng2-bootstrap

### ISSUE THREAD

**Issue by CGuu** [joost-de-vries/play-angular2-typescript#25]
how to use libarary.such as ng2-bootstrap

**Comment by CGuu** [comment]
hi 
i use this play-angular2-typescript,and i add  this library
 "org.webjars.npm" % "ng2-bootstrap" % "1.4.0"
![Uploading QQ图片20170329110141.png…]()

**Comment by joost-de-vries** [comment]
I don't think that's so much an sbt-typescript problem. Stackoverflow is your friend.
