### ISSUE TITLE
Dependencies are broken

### ISSUE THREAD

**Issue by epot** [joost-de-vries/play-angular2-typescript#28]
I am trying to use this template but got a dependency issue stating:

org.webjars.npm typescript 2.3.2 not found

It is indeed not present here: https://mvnrepository.com/artifact/org.webjars.npm/typescript.

**Comment by hkirk** [comment]
I've downgrade to 2.3.1 which seems to work.

**Comment by joost-de-vries** [comment]
I published the npm to webjars again. It's on the [webjars bintray](https://bintray.com/webjars/maven/org.webjars.npm%3Atypescript) now. It will appear on maven central later.
I added the webjars bintray as a repo so you should be able to use this right away.

**Comment by epot** [comment]
Yeah I did the same locally. Ok, good to know it'll work soon, thanks!
