### ISSUE TITLE
empty lib directory

### ISSUE THREAD

**Issue by ostmond** [joost-de-vries/play-angular2-typescript#30]
Hello Joost,

sorry for my question asked here. I saw in your html file there are references to the lib directory, e.g. "`<script type='text/javascript' src='@routes.Assets.versioned("lib/systemjs/dist/system-polyfills.js")'></script>`". But there is actually no such directory in your project. Therefore I got errors like "_GET 
http://127.0.0.1:9000/assets/lib/angular2/bundles/angular2-polyfills.js 404 not found_" in the Firefox console. Could you tell me how to create this directory and get the library files?
Thank you very much!
Best Regards
Wei

**Comment by joost-de-vries** [comment]
This is standard behaviour of the Play framework. Look up the Play documentation about Assets.
These things can be found in the `target/web/public` dir.
