### ISSUE TITLE
activator error   , please help me, thanks a lot

### ISSUE THREAD

**Issue by FunnyJok** [joost-de-vries/play-angular2-typescript#31]
![qq 20170627171920](https://user-images.githubusercontent.com/29245790/27580623-ce14a88c-5b5d-11e7-917f-acd41740c695.png)

**Comment by FunnyJok** [comment]
There was no error on the Windows system, but the error was reported on the Linux virtual machine

**Comment by joost-de-vries** [comment]
Activator has been deprecated. The replacement is `sbt new` with g8. This repo has been ported to that new g8 based approach. You'll need a recent sbt launcher installed.
Then see the readme.
