### ISSUE TITLE
unresolved dependency: org.webjars.npm#through

### ISSUE THREAD

**Issue by yohanfernand** [joost-de-vries/play-angular2-typescript#33]
Creation of the application template fails with an unresolved dependency

[2K[0m[[0minfo[0m] [0mResolving org.webjars.npm#jsesc;[0.5.0,0.6) ...[0m
[0m[[33mwarn[0m] [0m	::::::::::::::::::::::::::::::::::::::::::::::[0m
[0m[[33mwarn[0m] [0m	::          UNRESOLVED DEPENDENCIES         ::[0m
[0m[[33mwarn[0m] [0m	::::::::::::::::::::::::::::::::::::::::::::::[0m
[0m[[33mwarn[0m] [0m	:: org.webjars.npm#through;0: not found[0m
[0m[[33mwarn[0m] [0m	::::::::::::::::::::::::::::::::::::::::::::::[0m
[0m[[33mwarn[0m] [0m[0m


[err.txt](https://github.com/joost-de-vries/play-angular-typescript.g8/files/1150177/err.txt)

**Comment by joost-de-vries** [comment]
Tx. It's a dependency of a dependency of codelyzer that [has a strange npm version](https://github.com/chrisdickinson/cssauron/pull/10) `x.x.x`. Doesn't look like that will be fixed any time soon. So I had to disable codelyzer.
If you get the latest version of the project it will work again.
