### ISSUE TITLE
Runtime exception: Invalid regular expression

### ISSUE THREAD

**Issue by epot** [joost-de-vries/play-angular2-typescript#34]
I am trying to use this seed by running:

    sbt new joost-de-vries/play-angular-typescript.g8

And then (from the project folder):

    sbt run 

But I get a javascript exception when loading the page:

    Error: Invalid regular expression: missing /
    Evaluating http://localhost:9000/assets/systemjs-angular-loader.js
    Loading http://localhost:9000/assets/systemjs-angular-loader.js
    Instantiating http://localhost:9000/assets/app/main.js
    Loading assets/app/main.js

**Comment by epot** [comment]
I had to manually fix the regex in system-angular-loader.js, whereas it looks good in this github repo. I wonder what is happening !? Is sbt new doing strange things?

**Comment by joost-de-vries** [comment]
That's quite possible. I've just changed that sbt new shouldn't mess with .js and .css files. Can you try again?

**Comment by epot** [comment]
Much better :)
