### ISSUE TITLE
rxjs dependencies passed compilation but failed at runtime.

### ISSUE THREAD

**Issue by WayneWang12** [joost-de-vries/play-angular2-typescript#36]
Hi, I've created a template project from the `sbt new` command and try to run it with `sbt run`.

It started successfully but when I open it in browser, there occured the error in console:
```
TypeError: Subject_1.Subject is not a constructor
    at new HeroSearchComponent (hero-search.component.js:47)
    at createClass (core.umd.js:10960)
    at createDirectiveInstance (core.umd.js:10788)
    at createViewNodes (core.umd.js:12229)
    at callViewAction (
```

It seems that the rxjs is not loaded in runtime. But I've found it in the source `assets/lib/rxjs`. I don't know why. Wish that I can get some help from you. Many thanks!

**Comment by joost-de-vries** [comment]
I don't see the same problem when I run the application. 
Sounds like an Angular / SystemJs issue.

**Comment by WayneWang12** [comment]
That's strange... I just execute `sbt new joost-de-vries/play-angular-typescript.g8` and  then `sbt run`. 

When I open the browser, errors occured in the browser. I'm using Windows then. I'll see if this error happens in Ubuntu.

**Comment by WayneWang12** [comment]
@joost-de-vries Yes, no any problem in Ubuntu.................

I'll give up windows now... Thanks for your great work. It's really awesome.
