### ISSUE TITLE
Importing modules with index1

### ISSUE THREAD

**Issue by instantdelay** [joost-de-vries/play-angular2-typescript#9]
I'm using the index1 configuration for development (SystemJS downloads individual JavaScript files) but I can't seem to get loading of 3rd party libs to work.

I can import modules which are part of the angular2.js bundle since they are already loaded from the `<script>` tag and I can import my own modules but for everything else SystemJS tries the wrong URL.

E.g. `import { Http } from 'angular2/http'` causes SystemJS to try `localhost/angular2/http`.

It seems like the System.config in index1.html needs to be changed but I'm not sure how to fix it. There is no way to make a map entry that applies to all libs by default. I would need to change the imports in my typescript code to start with "lib/" but then the directory structure produced by sbt-typescript is wrong and sbt fails.

Any ideas? Or am I missing something?

**Comment by joost-de-vries** [comment]
Look at my upgrade to Angular 2 RC4 in the ts-20-preview branch. 
You can configure SystemJs with hints what paths to download dependencies it finds.
